name: bundler
description: A command-line tool that create bundle of assets
version: 0.0.1
maintainer: Koorosh
homepage: https://github.com/kooroshh/flutter-bundler

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: Bundler
        pluginClass: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  archive: ^3.3.5
  pointycastle: ^3.6.2
  encrypt: ^5.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.1
